import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
	{
		_id: uuid(),
		title: "Harry Potter Complete Set",
		author: "J.K. Rowling",
		originalPrice: 1450.0,
		discountPercent: 45,
		discountPrice: 451.0,
		totalRatings: 82150,
		totalStars: 4.8,
		genres: ["Fiction", "Fantasy", "Young Adult", "Adventure", "Childrens"],
		bookType: "Hardcover",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: true,
			},
		],
		coverImg:
			"https://prodimage.images-bn.com/lf?set=key%5Bresolve.pixelRatio%5D,value%5B1%5D&set=key%5Bresolve.width%5D,value%5B550%5D&set=key%5Bresolve.height%5D,value%5B10000%5D&set=key%5Bresolve.imageFit%5D,value%5Bcontainerwidth%5D&set=key%5Bresolve.allowImageUpscaling%5D,value%5B0%5D&product=path%5B/pimages/9780545162074_p3_v1%5D&call=url%5Bfile:common/decodeProduct.chain%5D",
		description: `Over 4000 pages of Harry Potter and his world, including all 7 books.\nAll seven eBooks in the multi-award winning, internationally bestselling Harry Potter series, available as one download with stunning cover art by Olly Moss. Enjoy the stories that have captured the imagination of millions worldwide.`,
	},
	{
		_id: uuid(),
		title: "7 Mindsets for Success, Happiness and Fulfilment",
		author: "Swami Mukundananda",
		originalPrice: 295.0,
		discountPercent: 23,
		discountPrice: 67.0,
		totalRatings: 372,
		totalStars: 4.5,
		genres: [
			"Non-Fiction",
			"Spirituality",
			"Self Help",
			"Philosophy",
			"Psychology",
		],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: true,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1569209892l/51987423._SX318_SY475_.jpg",
		description: `Thoughts and feelings that persist over time harden into an attitude. If you live with an attitude long enough, it becomes second nature—a mindset. The wrong mindset could lead you off the path of contentment, joy, enlightenment. The right one will point you to the road to success, to fulfilment and towards an extraordinary life.\n\nBlending science with Vedic scriptures, and logic with spiritual insight, Swami Mukundananda unravels the secrets of the 7 mindsets—seven techniques of training the mind and intellect and unlocking the immense potential within. `,
	},
	{
		_id: uuid(),
		title: "Love on the Brain",
		author: "Ali Hazelwood",
		originalPrice: 472.0,
		discountPercent: 44,
		discountPrice: 207.0,
		totalRatings: 879,
		totalStars: 4.4,
		genres: [
			"Romance",
			"Contemporary Romance",
			"Adult",
			"Fiction",
			"Academia",
		],
		bookType: "Paperback",
		inStock: false,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1642069168l/59571699._SY475_.jpg",
		description: `From the New York Times bestselling author of The Love Hypothesis comes a new STEMinist rom-com in which a scientist, Bee Königswasser, is forced to work on a project with her nemesis, Levi Ward—with explosive results.`,
	},
	{
		_id: uuid(),
		title: "Why We Sleep: Unlocking the Power of Sleep and Dreams",
		author: "Matthew Walker",
		originalPrice: 799.0,
		discountPercent: 15,
		discountPrice: 200.0,
		totalRatings: 129469,
		totalStars: 4.4,
		genres: [
			"Non-Fiction",
			"Neuroscience",
			"Health",
			"Psychology",
			"Self Help",
		],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1556604137l/34466963._SY475_.jpg",
		description: `Neuroscientist and sleep expert Matthew Walker provides a revolutionary exploration of sleep, examining how it affects every aspect of our physical and mental well-being. Charting the most cutting-edge scientific breakthroughs, and marshalling his decades of research and clinical practice, Walker explains how we can harness sleep to improve learning, mood and energy levels, regulate hormones, prevent cancer, Alzheimer's and diabetes, slow the effects of aging, and increase longevity. He also provides actionable steps towards getting a better night's sleep every night.`,
	},
	{
		_id: uuid(),
		title: "The Krishna Key",
		author: "Ashwin Sanghi",
		originalPrice: 450.0,
		discountPercent: 2,
		discountPrice: 10.0,
		totalRatings: 19017,
		totalStars: 3.6,
		genres: ["Fiction", "Thriller", "Mythology", "Historical", "Mystery"],
		bookType: "Paperback",
		inStock: false,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: false,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1341289060l/15733523.jpg",
		description: `Ashwin Sanghi brings you yet another exhaustively researched whopper of a plot, while providing an incredible alternative interpretation of the Vedic Age that will be relished by conspiracy buffs and thriller-addicts alike.\n\nHistorian Ravi Mohan Saini must breathlessly dash from the submerged remains of Dwarka and the mysterious lingam of Somnath to the icy heights of Mount Kailash, in a quest to discover the cryptic location of Krishna's most prized possession. From the sand-washed ruins of Kalibangan to a Vrindavan temple destroyed by Aurangzeb, Saini must also delve into antiquity to prevent a gross miscarriage of justice.`,
	},
	{
		_id: uuid(),
		title: "Atomic Habits",
		author: "James Clear",
		originalPrice: 999.0,
		discountPercent: 27,
		discountPrice: 300.0,
		totalRatings: 347170,
		totalStars: 4.6,
		genres: ["Non-Fiction", "Health", "Self Help", "Philosophy", "Science"],
		bookType: "Hardcover",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: true,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1535115320l/40121378._SY475_.jpg",
		description: `No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.`,
	},
	{
		_id: uuid(),
		title: "Attitude Is Everything",
		author: "Jeff Keller",
		originalPrice: 699.0,
		discountPercent: 14,
		discountPrice: 170.0,
		totalRatings: 2886,
		totalStars: 4.4,
		genres: [
			"Non-Fiction",
			"Slef Help",
			"Personal Development",
			"Leadership",
			"Motivational",
		],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: false,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1482649723l/33561786._SY475_.jpg",
		description: `This is a "success manual" that gives readers a step by step plan for taking control of their lives and unleashing their incredible potential. The book consists of 12 Lessons that was used by author Jeff Keller to make a career transition from lawyer to motivational speaker. The book shows readers how they, too, can make positive changes in every area of their lives.`,
	},
	{
		_id: uuid(),
		title: "The Book Theif",
		author: "Markus Zusak",
		originalPrice: 799.0,
		discountPercent: 29,
		discountPrice: 230.0,
		totalRatings: 2143296,
		totalStars: 4.4,
		genres: ["Historical", "Fiction", "Young Adult", "Classics", "War"],
		bookType: "Paperback",
        inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: true,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1522157426l/19063._SY475_.jpg",
		description: `It is 1939. Nazi Germany. The country is holding its breath. Death has never been busier, and will be busier still.\n\nBy her brother's graveside, Liesel's life is changed when she picks up a single object, partially hidden in the snow. It is The Gravedigger's Handbook, left behind there by accident, and it is her first act of book thievery. So begins a love affair with books and words, as Liesel, with the help of her accordian-playing foster father, learns to read. Soon she is stealing books from Nazi book-burnings, the mayor's wife's library, wherever there are books to be found.\n\nBut these are dangerous times. When Liesel's foster family hides a Jew in their basement, Liesel's world is both opened up, and closed down.`,
	},
	{
		_id: uuid(),
		title: "The Da Vinci Code",
		author: "Dan Brown",
		originalPrice: 499.0,
		discountPercent: 34,
		discountPrice: 169.0,
		totalRatings: 7686,
		totalStars: 4.6,
		genres: ["Fiction", "Mystery", "Thriller", "Suspense", "Adventure"],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: true,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1579621267l/968.jpg",
		description: `While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter.\n\nEven more startling, the late curator was involved in the Priory of Sion—a secret society whose members included Sir Isaac Newton, Victor Hugo, and Da Vinci—and he guarded a breathtaking historical secret. Unless Langdon and Neveu can decipher the labyrinthine puzzle—while avoiding the faceless adversary who shadows their every move—the explosive, ancient truth will be lost forever`,
	},
	{
		_id: uuid(),
		title: "Lean In: Women, Work, and the Will to Lead",
		author: "Sheryl Sandberg",
		originalPrice: 999.0,
		discountPercent: 15,
		discountPrice: 231.0,
		totalRatings: 243804,
		totalStars: 3.9,
		genres: [
			"Non-Fiction",
			"Feminism",
			"Leadership",
			"Business",
			"Autobiography",
		],
		bookType: "Hardcover",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: false,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630483761l/16071764._SY475_.jpg",
		description: `In Lean In, Sheryl Sandberg- Facebook COO and one of Fortune magazine's Most Powerful Women in Business- draws on her own experience of working in some of the world's most successful businesses and looks at what women can do to help themselves, and make the small changes in their life that can effect change on a more universal scale.`,
	},
	{
		_id: uuid(),
		title: "Divergent Series Complete Set",
		author: "Veronica Roth",
		originalPrice: 1599.0,
		discountPercent: 40,
		discountPrice: 637.0,
		totalRatings: 43526,
		totalStars: 3.2,
		genres: ["Dystopian", "Fiction", "Fantasy", "Romance", "Young Adult"],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: false,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1372682053l/17383994.jpg",
		description: `All three books in the #1 New York Times bestselling Divergent trilogy are available together for the first time! The collection includes Divergent, Insurgent, and Allegiant, as well as bonus content: a 48-page guide to the series, including Faction Manifestos, a Faction Quiz and Results, a Q&A with Veronica Roth, playlists, discussion questions, series inspirations, and much more!`,
	},
	{
		_id: uuid(),
		title: "A Man Called Ove",
		author: "Fredrik Backman",
		originalPrice: 599.0,
		discountPercent: 26,
		discountPrice: 129.0,
		totalRatings: 32852,
		totalStars: 4.5,
		genres: ["Fiction", "Contemporary", "Humor", "Adult", "Novel"],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: false,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1405259930l/18774964.jpg",
		description: `First, there were ten—a curious assortment of strangers summoned as weekend guests to a little private island off the coast of Devon. Their host, an eccentric millionaire unknown to all of them, is nowhere to be found. All that the guests have in common is a wicked past they're unwilling to reveal—and a secret that will seal their fate. For each has been marked for murder.\nWhen they realize that murders are occurring as described in the rhyme, terror mounts. One by one they fall prey. Before the weekend is out, there will be none. Who has choreographed this dastardly scheme? And who will be left to tell the tale? Only the dead are above suspicion. `,
	},
	{
		_id: uuid(),
		title: "And Then There Were None",
		author: "Agatha Christie",
		originalPrice: 199.0,
		discountPercent: 40,
		discountPrice: 79.0,
		totalRatings: 16870,
		totalStars: 4.2,
		genres: ["Mystery", "Classics", "Fiction", "Thriller", "Crime"],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: false,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1638425885l/16299._SY475_.jpg",
		description: ``,
	},
	{
		_id: uuid(),
		title: "Palace of Illusions",
		author: "Chitra Banerjee Divakaruni",
		originalPrice: 450.0,
		discountPercent: 42,
		discountPrice: 187.0,
		totalRatings: 42043,
		totalStars: 4.2,
		genres: ["Fiction", "Mythology", "Historical", "Retellins", "Cultural"],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1396229073l/1774836.jpg",
		description: `A reimagining of the world-famous Indian epic, the Mahabharat—told from the point of view of an amazing woman.\n\nRelevant to today's war-torn world, The Palace of Illusions takes us back to a time that is half history, half myth, and wholly magical. Narrated by Panchaali, the wife of the legendary Pandavas brothers in the Mahabharat, the novel gives us a new interpretation of this ancient tale.`,
	},
	{
		_id: uuid(),
		title: "Twilight",
		author: "Stephenie Meyer",
		originalPrice: 499.0,
		discountPercent: 20,
		discountPrice: 100.0,
		totalRatings: 5671177,
		totalStars: 2.7,
		genres: ["Fantasy", "Young Adult", "Romance", "Fiction", "Paranomal"],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1361039443l/41865.jpg",
		description: `About three things I was absolutely positive.\nFirst, Edward was a vampire.\nSecond, there was a part of him—and I didn't know how dominant that part might be—that thirsted for my blood.\nAnd third, I was unconditionally and irrevocably in love with him.\n\nDeeply seductive and extraordinarily suspenseful, Twilight is a love story with bite`,
	},
	{
		_id: uuid(),
		title: "Pride and Prejudice",
		author: "Jane Austen",
		originalPrice: 1299.0,
		discountPercent: 26,
		discountPrice: 334.0,
		totalRatings: 25340,
		totalStars: 4.6,
		genres: ["Classics", "Fiction", "Romance", "Historical", "Novel"],
		bookType: "Hardcover",
		inStock: false,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: true,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1320399351l/1885.jpg",
		description: `When Elizabeth Bennet meets Fitzwilliam Darcy for the first time at a ball, she writes him off as an arrogant and obnoxious man. He not only acts like an insufferable snob, but she also overhears him rejecting the very idea of asking her for a dance! As life pits them against each other again and again, Darcy begins to fall for Elizabeth's wit and intelligence and Elizabeth begins to question her feelings about Darcy. When Darcy saves her youngest sister, Lydia, from a scandal, Elizabeth starts to wonder if her pride has prejudiced her opinion of Darcy.`,
	},
	{
		_id: uuid(),
		title: "Wings of Fire",
		author: "Dr. A.P.J. Abdul Kalam and Arun Tiwari",
		originalPrice: 299.0,
		discountPercent: 36,
		discountPrice: 109.0,
		totalRatings: 46630,
		totalStars: 4.3,
		genres: [
			"Biography",
			"Non-Fiction",
			"Inspirational",
			"Science",
			"History",
		],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: false,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: true,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1588286863l/634583._SY475_.jpg",
		description: `This is the story of Kalam's rise from obscurity and his personal and professional struggles, as well as the story of Agni, Prithvi, Akash, Trishul and Nag-missiles that have become household names in India and that have raised the nation to the level of a missile power of international reckoning. This is also the saga of independent India's struggle for technological self-sufficiency and defensive autonomy-a story as much about politics, domestic and international, as it is about science`,
	},
	{
		_id: uuid(),
		title: "Love Hypothesis",
		author: "Ali Hazelwood",
		originalPrice: 493.0,
		discountPercent: 44,
		discountPrice: 216.0,
		totalRatings: 10256,
		totalStars: 4.7,
		genres: [
			"Romance",
			"Contemporary Romance",
			"Adult",
			"Fiction",
			"Academia",
		],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: false,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1611937942l/56732449.jpg",
		description: `As a third-year Ph.D. candidate, Olive Smith doesn't believe in lasting romantic relationships--but her best friend does, and that's what got her into this situation. Convincing Anh that Olive is dating and well on her way to a happily ever after was always going to take more than hand-wavy Jedi mind tricks: Scientists require proof. So, like any self-respecting biologist, Olive panics and kisses the first man she sees.\n\nThat man is none other than Adam Carlsen, a young hotshot professor who agrees to keep her charade a secret and be her fake boyfriend. Suddenly their little experiment feels dangerously close to combustion. And Olive discovers that the only thing more complicated than a hypothesis on love is putting her own heart under the microscope.`,
	},
	{
		_id: uuid(),
		title: "The Psychology of Money",
		author: "Morgan Housel",
		originalPrice: 399.0,
		discountPercent: 27,
		discountPrice: 109.0,
		totalRatings: 51051,
		totalStars: 4.4,
		genres: ["Economics", "Finance", "Psychology", "Business", "Self Help"],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: false,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: true,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1581527774l/41881472._SY475_.jpg",
		description: `Money—investing, personal finance, and business decisions—is typically taught as a math-based field, where data and formulas tell us exactly what to do. But in the real world people don't make financial decisions on a spreadsheet. They make them at the dinner table, or in a meeting room, where personal history, your own unique view of the world, ego, pride, marketing, and odd incentives are scrambled together.\n\nIn The Psychology of Money, award-winning author Morgan Housel shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life's most important topics`,
	},
	{
		_id: uuid(),
		title: "Harry Potter and the Cursed Child: Parts One and Two",
		author: "John Tiffany (Adaptation), Jack Thorne, J.K. Rowling",
		originalPrice: 399.0,
		discountPercent: 40,
		discountPrice: 159.0,
		totalRatings: 848359,
		totalStars: 1.9,
		genres: ["Fiction", "Fantasy", "Young Adult", "Adventure", "Childrens"],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: false,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1470082995l/29056083._SY475_.jpg",
		description: `It was always difficult being Harry Potter and it isn’t much easier now that he is an overworked employee of the Ministry of Magic, a husband and father of three school-age children.\n\nWhile Harry grapples with a past that refuses to stay where it belongs, his youngest son Albus must struggle with the weight of a family legacy he never wanted. As past and present fuse ominously, both father and son learn the uncomfortable truth: sometimes, darkness comes from unexpected places.`,
	},
	{
		_id: uuid(),
		title: "The Courage to Be Disliked",
		author: "Ichiro Kishimi and Fumitake Koga",
		originalPrice: 499.0,
		discountPercent: 32,
		discountPrice: 160.0,
		totalRatings: 36382,
		totalStars: 4.1,
		genres: [
			"Non-Fiction",
			"Self Help",
			"Philosophy",
			"Psychology",
			"Mental Health",
		],
		bookType: "Hardcover",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: false,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: true,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1545421684l/43306206._SY475_.jpg",
		description: `The Courage to be Disliked shows you how to unlock the power within yourself to become your best and truest self, change your future and find lasting happiness. Using the theories of Alfred Adler, one of the three giants of 19th century psychology alongside Freud and Jung, the authors explain how we are all free to determine our own future free of the shackles of past experiences, doubts and the expectations of others. It’s a philosophy that’s profoundly liberating, allowing us to develop the courage to change, and to ignore the limitations that we and those around us can place on ourselves.`,
	},
	{
		_id: uuid(),
		title: "City of Bones",
		author: "Cassandra Clare",
		originalPrice: 450.0,
		discountPercent: 25,
		discountPrice: 124.0,
		totalRatings: 22751,
		totalStars: 2.4,
		genres: ["Fantasy", "Young Adult", "Romance", "Paranomal", "Fiction"],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1432730315l/256683._SY475_.jpg",
		description: `When fifteen-year-old Clary Fray heads out to the Pandemonium Club in New York City, she hardly expects to witness a murder― much less a murder committed by three teenagers covered with strange tattoos and brandishing bizarre weapons. Then the body disappears into thin air. It's hard to call the police when the murderers are invisible to everyone else and when there is nothing―not even a smear of blood―to show that a boy has died. Or was he a boy?`,
	},
	{
		_id: uuid(),
		title: "To Kill a Mockingbird",
		author: "Harper Lee",
		originalPrice: 559.0,
		discountPercent: 39,
		discountPrice: 232.0,
		totalRatings: 5202423,
		totalStars: 3.7,
		genres: [
			"Fiction",
			"Classics",
			"Historical",
			"Academic",
			"Young Adult",
		],
		bookType: "Paperback",
		inStock: false,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: true,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1553383690l/2657.jpg",
		description: `Compassionate, dramatic, and deeply moving, "To Kill A Mockingbird" takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.`,
	},
	{
		_id: uuid(),
		title: "The Great Railway Bazaar",
		author: "Paul Theroux",
		originalPrice: 399.0,
		discountPercent: 37,
		discountPrice: 140.0,
		totalRatings: 18293,
		totalStars: 3.5,
		genres: [
			"Travel",
			"Non-Fiction",
			"Cultural",
			"Autobiography",
			"Classics",
		],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1440437557l/63689._SY475_.jpg",
		description: `First published in 1975, Paul Theroux's strange, unique, and hugely entertaining railway odyssey has become a modern classic of travel literature. Here Theroux recounts his early adventures on an unusual grand continental tour. Brimming with Theroux's signature humor and wry keen observations, this engrossing chronicle is essential reading for both the ardent adventurer and the armchair traveler.`,
	},
	{
		_id: uuid(),
		title: "House of Sky and Breath",
		author: "Sarah J. Maas",
		originalPrice: 799.0,
		discountPercent: 34,
		discountPrice: 270.0,
		totalRatings: 59559,
		totalStars: 4.6,
		genres: ["Fantasy", "Romance", "Adult", "Fairies", "Fiction"],
		bookType: "Paperback",
		inStock: true,
		offers: [
			{
				id: 1,
				offer: "fastDelivery",
				offerText: "Fast Delivery",
				isOffer: true,
			},
			{
				id: 2,
				offer: "newArrival",
				offerText: "New Arrival",
				isOffer: false,
			},
			{
				id: 3,
				offer: "bestSeller",
				offerText: "Best Seller",
				isOffer: false,
			},
		],
		coverImg:
			"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1633097753l/40132775._SY475_.jpg",
		description: `Bryce Quinlan and Hunt Athalar are trying to get back to normal―they may have saved Crescent City, but with so much upheaval in their lives lately, they mostly want a chance to relax. Slow down. Figure out what the future holds.\nIn this action-packed sequel to the #1 bestseller House of Earth and Blood, Sarah J. Maas weaves a captivating story of a world about to explode―and the people who will do anything to save it.`,
	},
];
